# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='clientName',
            field=models.CharField(default='erfg', max_length=50),
            preserve_default=False,
        ),
    ]
