# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinela', '0002_certificado_clientname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='keyName',
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certName',
            field=models.CharField(max_length=255),
        ),
    ]
