# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sentinela', '0004_auto_20170720_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Identificador'),
        ),
    ]
