# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 22:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentinela', '0005_auto_20170720_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central',
            name='certificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sentinela.Certificado'),
        ),
        migrations.AlterField(
            model_name='central',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sentinela.Empresa'),
        ),
        migrations.AlterField(
            model_name='enderecoempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sentinela.Empresa'),
        ),
        migrations.AlterField(
            model_name='enderecousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='telefoneempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sentinela.Empresa'),
        ),
        migrations.AlterField(
            model_name='telefoneusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
