# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentinela', '0007_auto_20170720_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sentinela.Empresa'),
        ),
    ]
