# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinela', '0008_auto_20170720_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='central',
            old_name='nome',
            new_name='descricao',
        ),
    ]
