# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='tipo',
            field=models.CharField(max_length=12),
        ),
    ]
