# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('rw', models.IntegerField(choices=[('R', 1), ('RW', 2)], default=1)),
            ],
            options={
                'verbose_name': 'Regra',
                'verbose_name_plural': 'Regras',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('pw', models.CharField(max_length=255)),
                ('super', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuario',
            },
        ),
    ]
