# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Tópico')),
                ('rw', models.IntegerField(choices=[(1, 'Leitura'), (2, 'Leitura e gravação')], default=1, verbose_name='Tipo de acesso')),
            ],
            options={
                'verbose_name': 'Regra',
                'verbose_name_plural': 'Regras',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Usuário')),
                ('pw', models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha')),
                ('publickey', models.CharField(blank=True, max_length=300, null=True, verbose_name='Chave pública')),
                ('super', models.BooleanField(default=False, verbose_name='Super usuário')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='acl',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mqtt.User', to_field='username', verbose_name='Usuário'),
        ),
    ]
