# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='rw',
            field=models.IntegerField(choices=[(1, 'Leitura'), (2, 'Leitura e gravação')], default=1, verbose_name='Leitura / Gravação'),
        ),
        migrations.AlterField(
            model_name='acl',
            name='topic',
            field=models.CharField(max_length=255, verbose_name='Tópico'),
        ),
        migrations.AlterField(
            model_name='acl',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pw',
            field=models.CharField(max_length=255, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='user',
            name='super',
            field=models.BooleanField(default=False, verbose_name='Super usuário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Usuário'),
        ),
    ]
