# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0002_auto_20170708_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Usuário'),
        ),
    ]
