# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0003_auto_20170708_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mqtt.User', to_field='username', verbose_name='Usuário'),
        ),
    ]
