# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0004_auto_20170708_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='publickey',
            field=models.CharField(blank=True, max_length=270, null=True, verbose_name='Chave pública'),
        ),
        migrations.AlterField(
            model_name='acl',
            name='rw',
            field=models.IntegerField(choices=[(1, 'Leitura'), (2, 'Leitura e gravação')], default=1, verbose_name='Tipo de acesso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pw',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha'),
        ),
    ]
